-- 📝 BACKUP SIMPLE PARA COPIAR/PEGAR
-- Este script usa PRINT para facilitar el copiado de resultados

PRINT '=== BACKUP BASE DE DATOS ATAPUERCA ===';
PRINT 'Fecha: ' + CAST(GETDATE() AS VARCHAR);
PRINT 'Base de datos: ' + DB_NAME();
PRINT '';

-- 1. TABLAS DISPONIBLES
PRINT '=== TABLAS DISPONIBLES ===';
DECLARE @tablas VARCHAR(MAX) = '';
SELECT @tablas = @tablas + TABLE_NAME + CHAR(13) + CHAR(10)
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;
PRINT @tablas;

-- 2. ESTRUCTURA DE BASES
PRINT '=== ESTRUCTURA TABLA BASES ===';
DECLARE @estructura VARCHAR(MAX) = '';
SELECT @estructura = @estructura + 
    COLUMN_NAME + ' (' + DATA_TYPE + 
    CASE WHEN CHARACTER_MAXIMUM_LENGTH IS NOT NULL 
         THEN '(' + CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) + ')' 
         ELSE '' END + ')' + CHAR(13) + CHAR(10)
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Bases'
ORDER BY ORDINAL_POSITION;
PRINT @estructura;

-- 3. DATOS DE BASES (primeros 10 registros)
PRINT '=== DATOS TABLA BASES (MUESTRA) ===';
SELECT TOP 10 * FROM Bases;

-- 4. VERIFICAR OTRAS TABLAS COMUNES
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Supervivientes')
    PRINT 'EXISTE: Tabla Supervivientes'
ELSE IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Survivors')
    PRINT 'EXISTE: Tabla Survivors'
ELSE
    PRINT 'NO ENCONTRADA: Tabla de supervivientes';

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Recursos')
    PRINT 'EXISTE: Tabla Recursos'
ELSE IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Resources')
    PRINT 'EXISTE: Tabla Resources'
ELSE
    PRINT 'NO ENCONTRADA: Tabla de recursos';

PRINT '';
PRINT '=== INSTRUCCIONES ===';
PRINT '1. Copia todos estos resultados';
PRINT '2. Pégalos en un archivo de texto';
PRINT '3. Compártelos con GitHub Copilot';
