-- � SCRIPT DE BACKUP COMPLETO DE LA BASE DE DATOS ATAPUERCA
-- Este script generará un backup completo que GitHub Copilot podrá leer y analizar

-- ===== PARTE 1: INFORMACIÓN DE METADATOS =====

-- 1. INFORMACIÓN GENERAL DE LA BASE DE DATOS
SELECT '=== INFORMACIÓN GENERAL ===' AS Seccion;
SELECT 
    DB_NAME() AS NombreBaseDatos,
    GETDATE() AS FechaBackup,
    USER_NAME() AS Usuario;

-- 2. LISTA COMPLETA DE TODAS LAS TABLAS
SELECT '=== TODAS LAS TABLAS DISPONIBLES ===' AS Seccion;
SELECT 
    TABLE_SCHEMA AS Esquema,
    TABLE_NAME AS Tabla,
    TABLE_TYPE AS Tipo
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

-- ===== PARTE 2: ESTRUCTURA COMPLETA DE CADA TABLA =====

-- 3. ESTRUCTURA DE TODAS LAS TABLAS
SELECT '=== ESTRUCTURA DE TODAS LAS TABLAS ===' AS Seccion;
SELECT 
    t.TABLE_NAME AS Tabla,
    c.COLUMN_NAME AS Columna,
    c.DATA_TYPE AS TipoDato,
    c.IS_NULLABLE AS AceptaNulos,
    c.CHARACTER_MAXIMUM_LENGTH AS LongitudMax,
    c.NUMERIC_PRECISION AS Precision,
    c.ORDINAL_POSITION AS Posicion
FROM INFORMATION_SCHEMA.TABLES t
INNER JOIN INFORMATION_SCHEMA.COLUMNS c ON t.TABLE_NAME = c.TABLE_NAME
WHERE t.TABLE_TYPE = 'BASE TABLE'
ORDER BY t.TABLE_NAME, c.ORDINAL_POSITION;

-- ===== PARTE 3: BACKUP COMPLETO DE DATOS =====

-- 4. DATOS COMPLETOS DE LA TABLA BASES (si existe)
SELECT '=== DATOS TABLA BASES ===' AS Seccion;
SELECT * FROM Bases;

-- 5. INTENTAR OBTENER DATOS DE POSIBLES TABLAS DE SUPERVIVIENTES
-- Nota: Una de estas consultas funcionará según el nombre real de la tabla

-- Posible nombre: Supervivientes
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Supervivientes')
BEGIN
    SELECT '=== DATOS TABLA SUPERVIVIENTES ===' AS Seccion;
    SELECT * FROM Supervivientes;
END

-- Posible nombre: Survivors
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Survivors')
BEGIN
    SELECT '=== DATOS TABLA SURVIVORS ===' AS Seccion;
    SELECT * FROM Survivors;
END

-- Posible nombre: People
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'People')
BEGIN
    SELECT '=== DATOS TABLA PEOPLE ===' AS Seccion;
    SELECT * FROM People;
END

-- 6. INTENTAR OBTENER DATOS DE POSIBLES TABLAS DE RECURSOS
-- Posible nombre: Recursos
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Recursos')
BEGIN
    SELECT '=== DATOS TABLA RECURSOS ===' AS Seccion;
    SELECT * FROM Recursos;
END

-- Posible nombre: Resources
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Resources')
BEGIN
    SELECT '=== DATOS TABLA RESOURCES ===' AS Seccion;
    SELECT * FROM Resources;
END

-- Posible nombre: Supplies
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Supplies')
BEGIN
    SELECT '=== DATOS TABLA SUPPLIES ===' AS Seccion;
    SELECT * FROM Supplies;
END

-- ===== PARTE 4: ANÁLISIS DE RELACIONES =====

-- 7. ANÁLISIS DE CLAVES FORÁNEAS
SELECT '=== CLAVES FORÁNEAS DETECTADAS ===' AS Seccion;
SELECT 
    fk.TABLE_NAME AS TablaOrigen,
    fk.COLUMN_NAME AS ColumnaOrigen,
    pk.TABLE_NAME AS TablaDestino,
    pk.COLUMN_NAME AS ColumnaDestino,
    fk.CONSTRAINT_NAME AS NombreRelacion
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE fk 
    ON rc.CONSTRAINT_NAME = fk.CONSTRAINT_NAME
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE pk 
    ON rc.UNIQUE_CONSTRAINT_NAME = pk.CONSTRAINT_NAME
ORDER BY fk.TABLE_NAME;

-- ===== PARTE 5: ESTADÍSTICAS GENERALES =====

-- 8. CONTEO DE REGISTROS EN TODAS LAS TABLAS
SELECT '=== CONTEO DE REGISTROS POR TABLA ===' AS Seccion;

DECLARE @sql NVARCHAR(MAX) = '';
SELECT @sql = @sql + 'SELECT ''' + TABLE_NAME + ''' AS Tabla, COUNT(*) AS NumeroRegistros FROM ' + TABLE_NAME + ' UNION ALL ' + CHAR(13)
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE';

-- Quitar el último UNION ALL
SET @sql = LEFT(@sql, LEN(@sql) - 11);

EXEC sp_executesql @sql;

-- ===== INSTRUCCIONES DE USO =====
SELECT '=== INSTRUCCIONES ===' AS Seccion;
SELECT 'Ejecuta este script completo y guarda todos los resultados en un archivo de texto.' AS Instruccion
UNION ALL
SELECT 'Luego comparte ese archivo con GitHub Copilot para análisis completo.' AS Instruccion
UNION ALL  
SELECT 'Esto permitirá crear los retos SQL perfectamente adaptados a tu base de datos.' AS Instruccion;